---
- hosts: all
  vars_files:
    - vars/common.yml
  remote_user: vagrant
  roles:
  - {role: nginx, become: yes}
  - {role: ansible-role-nodejs, become: yes}
  - {role: ansible-role-mongodb, become: yes}
  - {role: common, become: yes}
  - {role: redis, become: yes}
